### ISSUE TITLE
voka

### ISSUE THREAD

**Issue by dimaruu** [Nexterr/simpleTV-scripts#4]
Привет мне сказали ты  делал скрипт на voka
Может есть  возможность как то регионалки  добавить тоже 
Регионалки доступны по регионам
Если нужна помощь я могу попробовать помоч тебе
Я с Могилева
У меня доступны некоторые регионалки...

**Comment by heezer448** [comment]
не всё так просто

вт, 5 янв. 2021 г. в 21:36, dimaruu <notifications@github.com>:

**Comment by dimaruu** [comment]
Региональная блокировка?

**Comment by dimaruu** [comment]
А в чем проблема добавить?
Там что то по другому работает?
Как я понял  скрипт    обновляет   потоки  с сайта вока

**Comment by dimaruu** [comment]
Я  это же писал   в  группу  ТВ Портал М24 Луганск/ SimpleTV-M24  они  не смогли даже   завести эти  потоки  и сослались на региональную блокировку

**Comment by Nexterr** [comment]
> как то регионалки добавить тоже

откуда?

**Comment by dimaruu** [comment]
Я могу достать их с своего региона и скинуть тебе 
Но мне сказали там региональная блокировка  и работать  не у кого они не будут кроме меня
Я про регионалки Бобруйск 360 Беларусь 4 и тд 
Ты то их даже в глаза наверно не видел...

**Comment by Nexterr** [comment]
>  не видел

вобще без понятия



> достать их с своего региона

то есть?
пример ссылки?

**Comment by dimaruu** [comment]
[Новый текстовый документ (2).txt](https://github.com/Nexterr/simpleTV-scripts/files/5775873/2.txt)

**Comment by dimaruu** [comment]
там 2 ссылки для  потоков с моего региона

**Comment by Nexterr** [comment]
стримы в dash c drm,
нужны id каналов типа 114d4fec-f01d-436e-2fc7-c49925496f01

**Comment by dimaruu** [comment]
https://streaming-iptv.voka.tv/eyJvc19uYW1lIjoiV2luZG93cyIsInVzZXJfdWlkIjoiZTBlNWY5MTgtYjBkNC00ZWVkLTgzZWItYTllMzEzYWRjNmExIiwicHJvdG9jb2wiOiJkYXNoIiwiZHJtIjoic3BidHZjYXMiLCJzZXNzaW9uX2lkIjoiNjYyZWZlOGYtZTdiNS00NWM3LWJkNjQtNDU0ZTNiNjFkYjM0IiwiZG9tYWluX25hbWUiOiJzdHJlYW1pbmctaXB0di52b2thLnR2IiwiaXBfYWRkcmVzcyI6IjEwLjY0LjI4Ljk1IiwiZXhwaXJhdGlvbl9kYXRlIjoiMjAyMS0wMS0wN1QxNDo0ODo1MVoiLCJzdHJlYW1fbmFtZSI6IjYyMzkiLCJzdHJlYW1fcGF0aCI6Ii9pcF92NSIsImRhdGFjZW50ZXIiOiJpbnQifQ%3D%3D/MC0CFQCUemJsPjd1hvaCpUT0w82x5kNTAgIUA5kc143SMqBhl2aY7w0Xk4-vZwE%3D/ip_v5/6239.mpd?b_app_channel_id=b6e5c81e-9175-4357-86e4-fe76949a066c&b_app_id=voka_production&b_device_platform=Windows&b_device_uid=3db55f2d-502f-498c-43a9-a2815a303464&b_stream_sid=662efe8f-e7b5-45c7-bd64-454e3b61db34&b_strmr_channel_id=6239&stream_dvr_window=7200000000

вот это?

Если нет...подскажи как их получить   ?

**Comment by Nexterr** [comment]
эта ссылка работает
но с этим channel_id скрипт нет
https://www.voka.tv/b6e5c81e-9175-4357-86e4-fe76949a066c
смотрите какой запрос идет для получения ссылки

**Comment by dimaruu** [comment]
Я не правильную ссылку скинул или все же есть  какая то блокировка на регионалки?

**Comment by dimaruu** [comment]
На сайте регионалки только  доступны    только    для своего региона
Я например с Могилева
Другой кто    зайдет по ссылке  https://www.voka.tv/channels/bobruisk-360  получит ошибку  что канала такого нет
Аналогично видимо и с потоками
Если   мне дадут  на любой канал для другого региона я так же получу ошибку
Меня  интересовал  вопрос....можно ли это как то обойти?

**Comment by Nexterr** [comment]
> обойти

врядли, блокировка по ip

**Comment by dimaruu** [comment]
Ясно. Спасибо что  попытался  помочь.
