### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by FoxMcLout** [Nexterr/simpleTV-scripts#5]
Привет .Заметил что перестали работать скрипты TV+ HD и ДомаТВнет .
Спасибо большое что продолжаешь заниматься этим неблагодарным делом) писать замечательные скрипты и скраперы.
Только на тебе и держится симплтв . Удачи тебе и здоровия в новом году!

**Comment by Nexterr** [comment]
ДомаТВнет работает

**Comment by Nexterr** [comment]
проверте  TV+, на некоторых каналах архив вроде работает
